### ISSUE TITLE
create stopgap list of endpoints to access regex PIDs

### ISSUE THREAD

**Issue by ksonda** [internetofwater/pids.geoconnex.us#8]
In the short term, need a machine-readable list of endpoints in a consistent format to get the list of PIDs that are regex in the PID server db, so that @webb-ben can automate the production of sitemap.xml in #7.

The most obvious candidate is to just use the NLDI endpoints, but the NWIS and WQP and huc12 and comid ones don't use geoconnex pids as uri currently. Thoughts @dblodgett-usgs?

**Comment by webb-ben** [comment]
https://ose.newmexicowaterdata.org/FROST-Server/v1.1/Locations?$count=true&$select=properties
